Default: &defaults
  user: user
  password: pass
  host: localhost
  database: RecipeYesod
  connections: 10

Development:
  <<: *defaults

Testing:
  database: RecipeYesod_test
  <<: *defaults

Staging:
  database: RecipeYesod_staging
  connections: 100
  <<: *defaults

Production:
  database: RecipeYesod_production
  connections: 100
  host: localhost
  <<: *defaults
